### ISSUE TITLE
"Collect attachments in current note" does not do anything?

### ISSUE THREAD

**Issue by luckman212** [RainCat1998/obsidian-custom-attachment-location#75]
I saw https://github.com/RainCat1998/obsidian-custom-attachment-location/issues/66 but when I execute the _Collect attachments in current note_ command (`collectAttachmentsCurrentNote`), nothing happens. Nothing is renamed, moved etc. Nothing shown in console either.

Obsidian 1.7.0 + Plugin ver 4.5.0

**Comment by luckman212** [comment]
Unless I am misunderstanding the purpose of this command?

**Comment by Ryoga1016** [comment]
Try agin, me too

**Comment by mnaoumov** [comment]
@luckman212 @Ryoga1016 Cannot reproduce the issue. Please provide a sample vault and a video with the issue

**Comment by luckman212** [comment]
@mnaoumov I created a test vault using an example note/attachments from my main vault where I can reproduce the issue. Here it is, just unzip, open the vault, and run the "Collect attachments in current note" command...

[zzzDelete.zip](https://github.com/user-attachments/files/16581430/zzzDelete.zip) ← vault

![screen](https://github.com/user-attachments/assets/4f65bae9-9fb8-4f13-bc6c-785d6dd8cf6a)

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.6.0

**Comment by luckman212** [comment]
@mnaoumov Thank you for this. I tested v4.6.0 on my main vault and initially it appeared to still not be doing anything. Then, I tested it on another vault and realized it WAS running, but it was not renaming any image files during this process. Only moves/collection. 

I guess that makes sense, but I thought running this command would also rename any linked images to the consistent format (same as drag&drop or paste). If that is not the intended function, then maybe I also need to install the other plugin? https://github.com/dy-sh/obsidian-consistent-attachments-and-links
